# Generated by Django 5.0.3 on 2026-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHit',
            fields=[
            ],
            options={
                'verbose_name': 'Site Hit',
                'verbose_name_plural': 'Site Hits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('activity_logs.activitylog',),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ACCESS', 'Access'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SUBMIT', 'Submit'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
