# Generated by Django 5.0.3 on 2026-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0003_activitylog_country_activitylog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
