# Generated by Django 4.2 on 2026-02-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organisation_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
