# Generated by Django 6.0.2 on 2026-02-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
