# Generated by Django 6.0.2 on 2026-02-07 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_rejected_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
