# Generated by Django 4.2 on 2026-02-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expedition_admin_type',
            field=models.CharField(blank=True, choices=[('antarctic', 'Antarctic'), ('arctic', 'Arctic'), ('southern_ocean', 'Southern Ocean'), ('himalaya', 'Himalaya')], max_length=30, null=True, verbose_name='Admin for Expedition Type'),
        ),
    ]
