# Generated by Django 6.0.2 on 2026-02-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_expedition_admin_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_role', models.CharField(blank=True, max_length=30, null=True)),
                ('account_status', models.CharField(blank=True, max_length=15, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_ts', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_ts', models.CharField(blank=True, max_length=255, null=True)),
                ('data_access_id', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('emailvarified', models.CharField(blank=True, max_length=255, null=True)),
                ('emailtoken', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('ppurl', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('known_as', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_mobile_no', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_login',
                'managed': False,
            },
        ),
    ]
