# Generated by Django 6.0.2 on 2026-03-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_login_attempt_otp_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='token_b64',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
