# Generated by Django 4.2 on 2026-02-06 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField(max_length=2000)),
                ('purpose', models.TextField(max_length=2000)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('keywords', models.TextField(help_text='Comma separated keywords (GCMD recommended)')),
                ('topic', models.CharField(max_length=200)),
                ('data_center', models.CharField(default='National Polar Data Center', max_length=200)),
                ('expedition_type', models.CharField(choices=[('antarctic', 'Antarctic'), ('arctic', 'Arctic'), ('southern_ocean', 'Southern Ocean'), ('himalaya', 'Himalaya')], max_length=30)),
                ('expedition_year', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=9)),
                ('expedition_number', models.CharField(blank=True, max_length=100)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('agriculture', 'Agriculture'), ('atmosphere', 'Atmosphere'), ('cryosphere', 'Cryosphere'), ('oceans', 'Oceans'), ('marine_science', 'Marine Science')], max_length=50)),
                ('iso_topic', models.CharField(choices=[('climatologyMeteorologyAtmosphere', 'Climatology/Meteorology/Atmosphere'), ('oceans', 'Oceans'), ('environment', 'Environment'), ('geoscientificInformation', 'Geoscientific Information'), ('imageryBaseMapsEarthCover', 'Imagery/Base Maps/Earth Cover')], max_length=100)),
                ('data_set_progress', models.CharField(choices=[('planned', 'Planned'), ('in_work', 'In Work'), ('complete', 'Complete')], max_length=20)),
                ('temporal_start_date', models.DateField()),
                ('temporal_end_date', models.DateField()),
                ('west_longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('east_longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('south_latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('north_latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('data_file', models.FileField(upload_to='datasets/')),
                ('metadata_file', models.FileField(blank=True, upload_to='metadata/')),
                ('readme_file', models.FileField(blank=True, upload_to='readme/')),
                ('file_size_mb', models.FloatField(default=0)),
                ('number_of_files', models.IntegerField(default=1)),
                ('access_type', models.CharField(choices=[('open', 'Open Access'), ('restricted', 'Restricted Access'), ('embargoed', 'Embargoed')], default='open', max_length=20)),
                ('embargo_date', models.DateField(blank=True, null=True)),
                ('license', models.CharField(max_length=200)),
                ('usage_restrictions', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]+$', 'Enter valid phone number')])),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ScientistDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]+$', 'Enter valid phone number')])),
                ('mobile', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Enter valid mobile number')])),
                ('institute', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4,10}$', 'Enter valid postal code')])),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientists', to='data_submission.datasetsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=200)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='data_submission.datasetsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='PaleoTemporalCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paleo_start_date', models.CharField(blank=True, max_length=50)),
                ('paleo_stop_date', models.CharField(blank=True, max_length=50)),
                ('chronostratigraphic_unit', models.CharField(blank=True, max_length=100)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paleo_temporal', to='data_submission.datasetsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='LocationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_category', models.CharField(choices=[('region', 'Region'), ('ocean', 'Ocean')], max_length=20)),
                ('location_type', models.CharField(max_length=50)),
                ('location_subregion', models.CharField(max_length=100)),
                ('other_subregion', models.CharField(blank=True, max_length=100)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='data_submission.datasetsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=200)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='data_submission.datasetsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='GPSMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_used', models.BooleanField(default=False)),
                ('minimum_altitude', models.CharField(blank=True, max_length=50)),
                ('maximum_altitude', models.CharField(blank=True, max_length=50)),
                ('minimum_depth', models.CharField(blank=True, max_length=50)),
                ('maximum_depth', models.CharField(blank=True, max_length=50)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='data_submission.datasetsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('series_name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('release_place', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('online_resource', models.URLField(blank=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citation', to='data_submission.datasetsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='DataResolutionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_resolution', models.CharField(blank=True, max_length=50)),
                ('longitude_resolution', models.CharField(blank=True, max_length=50)),
                ('horizontal_resolution_range', models.CharField(blank=True, max_length=50)),
                ('vertical_resolution', models.CharField(blank=True, max_length=50)),
                ('vertical_resolution_range', models.CharField(blank=True, max_length=50)),
                ('temporal_resolution', models.CharField(blank=True, max_length=50)),
                ('temporal_resolution_range', models.CharField(blank=True, max_length=50)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='data_submission.datasetsubmission')),
            ],
        ),
    ]
