# Generated by Django 4.2 on 2026-02-06 09:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataresolutionmetadata',
            options={'verbose_name': 'Data Resolution Metadata', 'verbose_name_plural': 'Data Resolution Metadata'},
        ),
        migrations.AlterModelOptions(
            name='datasetcitation',
            options={'verbose_name': 'Dataset Citation', 'verbose_name_plural': 'Dataset Citations'},
        ),
        migrations.AlterModelOptions(
            name='gpsmetadata',
            options={'verbose_name': 'GPS Metadata', 'verbose_name_plural': 'GPS Metadata'},
        ),
        migrations.AlterModelOptions(
            name='instrumentmetadata',
            options={'verbose_name': 'Instrument Metadata', 'verbose_name_plural': 'Instrument Metadata'},
        ),
        migrations.AlterModelOptions(
            name='locationmetadata',
            options={'verbose_name': 'Location Metadata', 'verbose_name_plural': 'Location Metadata'},
        ),
        migrations.AlterModelOptions(
            name='paleotemporalcoverage',
            options={'verbose_name': 'Paleo Temporal Coverage', 'verbose_name_plural': 'Paleo Temporal Coverage'},
        ),
        migrations.AlterModelOptions(
            name='platformmetadata',
            options={'verbose_name': 'Platform Metadata', 'verbose_name_plural': 'Platform Metadata'},
        ),
        migrations.AlterModelOptions(
            name='scientistdetail',
            options={'verbose_name': 'Scientist Detail', 'verbose_name_plural': 'Scientist Details'},
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='creator',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='editor',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='abstract',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='category',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('atmosphere', 'Atmosphere'), ('biological_classification', 'Biological Classification'), ('biosphere', 'Biosphere'), ('cryosphere', 'Cryosphere'), ('human_dimensions', 'Human Dimensions'), ('land_surface', 'Land Surface'), ('oceans', 'Oceans'), ('paleoclimate', 'Paleoclimate'), ('solid_earth', 'Solid Earth'), ('spectral_engineering', 'Spectral/Engineering'), ('sun_earth_interactions', 'Sun-Earth Interactions'), ('terrestrial_hydrosphere', 'Terrestrial Hydrosphere'), ('marine_science', 'Marine Science'), ('terrestrial_science', 'Terrestrial Science'), ('wind_profiler_radar', 'Wind Profiler Radar'), ('geotectonic_studies', 'Geotectonic Studies'), ('audio_signals', 'Audio Signals')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='contact_person',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s\\(\\)]+$', 'Enter valid phone number')]),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='data_file',
            field=models.FileField(blank=True, upload_to='datasets/'),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='expedition_year',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='iso_topic',
            field=models.CharField(choices=[('climatologyMeteorologyAtmosphere', 'Climatology/Meteorology/Atmosphere'), ('oceans', 'Oceans'), ('environment', 'Environment'), ('geoscientificInformation', 'Geoscientific Information'), ('imageryBaseMapsEarthCover', 'Imagery/Base Maps/Earth Cover'), ('inlandWaters', 'Inland Waters'), ('location', 'Location'), ('boundaries', 'Boundaries'), ('biota', 'Biota'), ('economy', 'Economy'), ('elevation', 'Elevation'), ('farming', 'Farming'), ('health', 'Health'), ('intelligenceMilitary', 'Intelligence/Military'), ('society', 'Society'), ('structure', 'Structure'), ('transportation', 'Transportation'), ('utilitiesCommunication', 'Utilities/Communication')], max_length=100),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='keywords',
            field=models.TextField(help_text='Comma separated keywords (GCMD recommended)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='purpose',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='title',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s\\(\\)]+$', 'Enter valid phone number')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='postal_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4,10}$', 'Enter valid postal code (4-10 digits)')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='role',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='title',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AddConstraint(
            model_name='datasetsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('doi__isnull', False), models.Q(('doi', ''), _negated=True)), fields=('doi',), name='unique_doi'),
        ),
    ]
