# Generated by Django 6.0.2 on 2026-02-06 20:19

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0002_alter_dataresolutionmetadata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='category',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('atmosphere', 'Atmosphere'), ('biological_classification', 'Biological Classification'), ('biosphere', 'Biosphere'), ('climate_indicators', 'Climate Indicators'), ('cryosphere', 'Cryosphere'), ('human_dimensions', 'Human Dimensions'), ('land_surface', 'Land Surface'), ('oceans', 'Oceans'), ('paleoclimate', 'Paleoclimate'), ('solid_earth', 'Solid Earth'), ('spectral_engineering', 'Spectral/Engineering'), ('sun_earth_interactions', 'Sun-Earth Interactions'), ('terrestrial_hydrosphere', 'Terrestrial Hydrosphere'), ('marine_science', 'Marine Science'), ('terrestrial_science', 'Terrestrial Science'), ('wind_profiler_radar', 'Wind Profiler Radar'), ('geotectonic_studies', 'Geotectonic Studies'), ('audio_signals', 'Audio Signals')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='data_set_progress',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_work', 'In Work'), ('complete', 'Complete')], max_length=20, verbose_name='Dataset Progress'),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='doi',
            field=models.CharField(blank=True, max_length=255, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='iso_topic',
            field=models.CharField(choices=[('climatologyMeteorologyAtmosphere', 'Climatology/Meteorology/Atmosphere'), ('oceans', 'Oceans'), ('environment', 'Environment'), ('geoscientificInformation', 'Geoscientific Information'), ('imageryBaseMapsEarthCover', 'Imagery/Base Maps/Earth Cover'), ('inlandWaters', 'Inland Waters'), ('location', 'Location'), ('boundaries', 'Boundaries'), ('biota', 'Biota'), ('economy', 'Economy'), ('elevation', 'Elevation'), ('farming', 'Farming'), ('health', 'Health'), ('intelligenceMilitary', 'Intelligence/Military'), ('society', 'Society'), ('structure', 'Structure'), ('transportation', 'Transportation'), ('utilitiesCommunication', 'Utilities/Communication')], max_length=100, verbose_name='ISO Topic'),
        ),
        migrations.AlterField(
            model_name='gpsmetadata',
            name='gps_used',
            field=models.BooleanField(default=False, verbose_name='GPS Used'),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
