# Generated by Django 6.0.2 on 2026-02-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0004_alter_datasetsubmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetsubmission',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='datasetsubmission',
            name='embargo_date',
        ),
        migrations.RemoveField(
            model_name='datasetsubmission',
            name='license',
        ),
        migrations.RemoveField(
            model_name='datasetsubmission',
            name='usage_restrictions',
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
