# Generated by Django 4.2.13 on 2026-02-09 21:15

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0006_enable_trigram'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datasetsubmission',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'abstract', 'keywords'], name='dataset_fts_gin_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='datasetsubmission',
            index=models.Index(fields=['expedition_type'], name='dataset_expedition_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetsubmission',
            index=models.Index(fields=['category'], name='dataset_category_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetsubmission',
            index=models.Index(fields=['status'], name='dataset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetsubmission',
            index=models.Index(fields=['expedition_year'], name='dataset_year_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetsubmission',
            index=models.Index(fields=['iso_topic'], name='dataset_iso_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetsubmission',
            index=models.Index(fields=['temporal_start_date', 'temporal_end_date'], name='dataset_temporal_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetsubmission',
            index=models.Index(fields=['west_longitude', 'east_longitude', 'south_latitude', 'north_latitude'], name='dataset_spatial_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetsubmission',
            index=models.Index(fields=['-submission_date'], name='dataset_submitted_idx'),
        ),
    ]
