# Generated by Django 4.2.13 on 2026-02-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datasetsubmission',
            name='unique_doi',
        ),
        migrations.RemoveField(
            model_name='datasetsubmission',
            name='doi',
        ),
    ]
