# Generated by Django 6.0 on 2026-02-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0008_remove_datasetsubmission_unique_doi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetsubmission',
            name='metadata_id',
            field=models.CharField(blank=True, help_text='Legacy metadata ID (e.g. MF-725396532)', max_length=50, null=True, unique=True, verbose_name='Metadata ID'),
        ),
    ]
