# Generated by Django 6.0 on 2026-02-27 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0009_datasetsubmission_metadata_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision', 'Needs Revision'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='DatasetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('institute', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('research_area', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('agree_cite', models.BooleanField(default=False)),
                ('agree_share', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='data_submission.datasetsubmission')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset Download Request',
                'verbose_name_plural': 'Dataset Download Requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
