# Generated by Django 6.0 on 2026-02-28 01:32

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0010_alter_datasetsubmission_status_datasetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.CharField(max_length=200, unique=True)),
                ('user_password', models.CharField(max_length=200)),
                ('user_role', models.CharField(blank=True, max_length=50, null=True)),
                ('account_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_ts', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_ts', models.CharField(blank=True, max_length=100, null=True)),
                ('data_access_id', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('organisation', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('emailvarified', models.CharField(blank=True, max_length=50, null=True)),
                ('emailtoken', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('ppurl', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('known_as', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_mobile_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Legacy User',
                'verbose_name_plural': 'Legacy Users',
            },
        ),
        migrations.AddField(
            model_name='dataresolutionmetadata',
            name='latitude_resolution_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dataresolutionmetadata',
            name='latitude_resolution_sec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dataresolutionmetadata',
            name='longitude_resolution_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dataresolutionmetadata',
            name='longitude_resolution_sec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='datasetcitation',
            name='presentation_form',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='access_constraints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='data_set_language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='dif_creation_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='dif_revision_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='distribution_fees',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='distribution_format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='distribution_media',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='distribution_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='future_dif_review_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='internal_directory_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='last_dif_revision_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='metadata_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='multimedia_sample_format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='multimedia_sample_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='originating_center',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='parent_dif',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='privacy_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='quality',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='related_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='related_url_content_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='related_url_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasetsubmission',
            name='use_constraints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_easternmost_longitude_deg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_easternmost_longitude_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_easternmost_longitude_sec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_northernmost_latitude_deg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_northernmost_latitude_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_northernmost_latitude_sec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_southernmost_latitude_deg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_southernmost_latitude_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_southernmost_latitude_sec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_westernmost_longitude_deg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_westernmost_longitude_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='g_westernmost_longitude_sec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_easternmost_longitude_deg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_easternmost_longitude_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_easternmost_longitude_sec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_northernmost_latitude_deg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_northernmost_latitude_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_northernmost_latitude_sec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_southernmost_latitude_deg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_southernmost_latitude_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_southernmost_latitude_sec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_westernmost_longitude_deg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_westernmost_longitude_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpsmetadata',
            name='p_westernmost_longitude_sec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scientistdetail',
            name='address2',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scientistdetail',
            name='country_raw',
            field=models.CharField(blank=True, help_text='Legacy raw country string', max_length=100),
        ),
        migrations.AddField(
            model_name='scientistdetail',
            name='fax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_short_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dc_long_name', models.CharField(blank=True, max_length=500, null=True)),
                ('dc_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('dc_address1', models.TextField(blank=True, null=True)),
                ('dc_address2', models.TextField(blank=True, null=True)),
                ('dc_city', models.CharField(blank=True, max_length=200, null=True)),
                ('dc_state', models.CharField(blank=True, max_length=200, null=True)),
                ('dc_postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_country', models.CharField(blank=True, max_length=200, null=True)),
                ('dc_email', models.CharField(blank=True, max_length=200, null=True)),
                ('dc_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_fax', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_centers', to='data_submission.datasetsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='NPDCMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.IntegerField(blank=True, null=True)),
                ('fileinfo_id', models.CharField(blank=True, max_length=200, null=True)),
                ('data_status', models.CharField(blank=True, max_length=100, null=True)),
                ('data_ref_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata_status', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='npdc_master', to='data_submission.datasetsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_author', models.TextField(blank=True, null=True)),
                ('ref_publication_date', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_title', models.TextField(blank=True, null=True)),
                ('ref_series', models.TextField(blank=True, null=True)),
                ('ref_report_number', models.CharField(blank=True, max_length=200, null=True)),
                ('ref_publication_place', models.CharField(blank=True, max_length=200, null=True)),
                ('ref_publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('ref_online_resource', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='data_submission.datasetsubmission')),
            ],
        ),
    ]
