# Generated by ChatGPT on 2026-02-28

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0011_legacyuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrequest',
            name='requester',
            field=models.ForeignKey(
                related_name='dataset_requests',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                help_text='Optional link to the user account that made this request.',
            ),
        ),
    ]
