# Generated by Django 6.0 on 2026-03-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0012_add_requester_to_datasetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrequest',
            name='location',
            field=models.CharField(blank=True, help_text='Location from where data is being downloaded', max_length=200, null=True),
        ),
    ]
