# Generated by Django 6.0 on 2026-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0013_datasetrequest_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetrequest',
            name='location',
        ),
        migrations.AddField(
            model_name='datasetrequest',
            name='request_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which the request was made', null=True),
        ),
        migrations.AddField(
            model_name='datasetrequest',
            name='request_location',
            field=models.CharField(blank=True, help_text='Location from which the request was made (extracted from IP)', max_length=500, null=True),
        ),
    ]
