# Generated by Django 6.0 on 2026-03-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0014_remove_datasetrequest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsubmission',
            name='iso_topic',
            field=models.CharField(choices=[('Atmosphere', 'Atmosphere'), ('Biodiversity and Biotechnological Potential', 'Biodiversity and Biotechnological Potential'), ('Biogeochemistry', 'Biogeochemistry'), ('Biota', 'Biota'), ('Boundaries', 'Boundaries'), ('Climatology/Meteorology/Atmosphere', 'Climatology/Meteorology/Atmosphere'), ('Cryosphere', 'Cryosphere'), ('Economy', 'Economy'), ('Environment', 'Environment'), ('Farming', 'Farming'), ('Geodesy', 'Geodesy'), ('Geoscience - GPS', 'Geoscience - GPS'), ('geoscientific Information', 'geoscientific Information'), ('Ionosphere', 'Ionosphere'), ('Major ions', 'Major ions'), ('Meteorology', 'Meteorology'), ('Nutrients', 'Nutrients'), ('Oceanography', 'Oceanography'), ('Oceans', 'Oceans'), ('Seismology', 'Seismology'), ('Stable Isotope', 'Stable Isotope'), ('Topography', 'Topography'), ('Trace metals', 'Trace metals'), ('Water Chemistry', 'Water Chemistry')], max_length=100, verbose_name='ISO Topic'),
        ),
    ]
