# Generated by Django 6.0 on 2026-03-03 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0015_alter_datasetsubmission_iso_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientistdetail',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
    ]
