# Generated by Django 6.0 on 2026-03-03 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0016_alter_scientistdetail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcitation',
            name='creator',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='editor',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='online_resource',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='presentation_form',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='release_place',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='series_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datasetcitation',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='metadata_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='project_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='address2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='institute',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='mobile',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Enter valid mobile number')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='role',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
    ]
