# Generated by Django 6.0 on 2026-03-03 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0017_alter_datasetcitation_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsubmission',
            name='abstract',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='category',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('atmosphere', 'Atmosphere'), ('biological_classification', 'Biological Classification'), ('biosphere', 'Biosphere'), ('climate_indicators', 'Climate Indicators'), ('cryosphere', 'Cryosphere'), ('human_dimensions', 'Human Dimensions'), ('land_surface', 'Land Surface'), ('oceans', 'Oceans'), ('paleoclimate', 'Paleoclimate'), ('solid_earth', 'Solid Earth'), ('spectral_engineering', 'Spectral/Engineering'), ('sun_earth_interactions', 'Sun-Earth Interactions'), ('terrestrial_hydrosphere', 'Terrestrial Hydrosphere'), ('marine_science', 'Marine Science'), ('terrestrial_science', 'Terrestrial Science'), ('wind_profiler_radar', 'Wind Profiler Radar'), ('geotectonic_studies', 'Geotectonic Studies'), ('audio_signals', 'Audio Signals')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')]),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='data_set_progress',
            field=models.CharField(blank=True, choices=[('planned', 'Planned'), ('in_work', 'In Work'), ('complete', 'Complete')], max_length=20, verbose_name='Dataset Progress'),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='east_longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='expedition_type',
            field=models.CharField(blank=True, choices=[('antarctic', 'Antarctic'), ('arctic', 'Arctic'), ('southern_ocean', 'Southern Ocean'), ('himalaya', 'Himalaya')], max_length=30),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='expedition_year',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='iso_topic',
            field=models.CharField(blank=True, choices=[('Atmosphere', 'Atmosphere'), ('Biodiversity and Biotechnological Potential', 'Biodiversity and Biotechnological Potential'), ('Biogeochemistry', 'Biogeochemistry'), ('Biota', 'Biota'), ('Boundaries', 'Boundaries'), ('Climatology/Meteorology/Atmosphere', 'Climatology/Meteorology/Atmosphere'), ('Cryosphere', 'Cryosphere'), ('Economy', 'Economy'), ('Environment', 'Environment'), ('Farming', 'Farming'), ('Geodesy', 'Geodesy'), ('Geoscience - GPS', 'Geoscience - GPS'), ('geoscientific Information', 'geoscientific Information'), ('Ionosphere', 'Ionosphere'), ('Major ions', 'Major ions'), ('Meteorology', 'Meteorology'), ('Nutrients', 'Nutrients'), ('Oceanography', 'Oceanography'), ('Oceans', 'Oceans'), ('Seismology', 'Seismology'), ('Stable Isotope', 'Stable Isotope'), ('Topography', 'Topography'), ('Trace metals', 'Trace metals'), ('Water Chemistry', 'Water Chemistry')], max_length=100, verbose_name='ISO Topic'),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma separated keywords (GCMD recommended)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='north_latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='project_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='project_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='purpose',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='south_latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='temporal_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='temporal_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='west_longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
