# Generated by Django 6.0 on 2026-03-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0018_alter_datasetsubmission_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmetadata',
            name='location_category',
            field=models.CharField(blank=True, choices=[('region', 'Region'), ('ocean', 'Ocean')], max_length=20),
        ),
        migrations.AlterField(
            model_name='locationmetadata',
            name='location_subregion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='locationmetadata',
            name='location_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
