# Generated by Django 6.0 on 2026-03-09 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0019_alter_locationmetadata_location_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsubmission',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter valid 10-digit phone number')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='mobile',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter valid 10-digit mobile number')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter valid 10-digit phone number')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='postal_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter valid 6-digit PIN code')]),
        ),
    ]
