# Generated by Django 6.0 on 2026-03-09 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0020_alter_datasetsubmission_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsubmission',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s\\(\\)]+$', 'Enter valid phone number with country code')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='mobile',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]+$', 'Enter valid mobile number with country code')]),
        ),
        migrations.AlterField(
            model_name='scientistdetail',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s\\(\\)]+$', 'Enter valid phone number with country code')]),
        ),
    ]
