# Generated by Django 6.0 on 2026-03-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0021_alter_datasetsubmission_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcitation',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
