# Generated by Django 6.0 on 2026-03-11 05:15

import data_submission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0023_alter_scientistdetail_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsubmission',
            name='data_file',
            field=models.FileField(blank=True, upload_to=data_submission.models.get_data_file_path),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='metadata_file',
            field=models.FileField(blank=True, upload_to=data_submission.models.get_metadata_file_path),
        ),
        migrations.AlterField(
            model_name='datasetsubmission',
            name='readme_file',
            field=models.FileField(blank=True, upload_to=data_submission.models.get_readme_file_path),
        ),
    ]
