# Generated by Django 5.0.3 on 2026-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_submission', '0024_alter_datasetsubmission_data_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsubmission',
            name='iso_topic',
            field=models.CharField(blank=True, choices=[('climatologyMeteorologyAtmosphere', 'Climatology/Meteorology/Atmosphere'), ('environment', 'Environment'), ('oceans', 'Oceans'), ('geoscientificInformation', 'Geoscientific Information'), ('geoscientific Information', 'Geoscientific Information (Alt)'), ('biota', 'Biota'), ('inlandWaters', 'Inland Waters'), ('farming', 'Farming'), ('boundaries', 'Boundaries'), ('economy', 'Economy'), ('Atmosphere', 'Atmosphere'), ('Biodiversity and Biotechnological Potential', 'Biodiversity and Biotechnological Potential'), ('Biogeochemistry', 'Biogeochemistry'), ('Cryosphere', 'Cryosphere'), ('Economy', 'Economy (Legacy)'), ('Environment', 'Environment (Legacy)'), ('Farming', 'Farming (Legacy)'), ('Geodesy', 'Geodesy'), ('Geoscience - GPS', 'Geoscience - GPS'), ('Ionosphere', 'Ionosphere'), ('Major ions', 'Major ions'), ('Meteorology', 'Meteorology'), ('Nutrients', 'Nutrients'), ('Oceanography', 'Oceanography'), ('Oceans', 'Oceans (Legacy)'), ('Seismology', 'Seismology'), ('Stable Isotope', 'Stable Isotope'), ('Topography', 'Topography'), ('Trace metals', 'Trace metals'), ('Water Chemistry', 'Water Chemistry')], max_length=100, verbose_name='ISO Topic'),
        ),
    ]
