# Generated by Django 4.2.13 on 2026-02-09 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, default='', max_length=500)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('is_zero_result', models.BooleanField(default=False)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['query'], name='searchlog_query_idx'), models.Index(fields=['is_zero_result'], name='searchlog_zero_idx'), models.Index(fields=['-timestamp'], name='searchlog_time_idx')],
            },
        ),
    ]
