# Generated by Django 5.0.3 on 2026-04-23 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(help_text='Name of the research vessel/ship', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\s\\.\\-\\&]+$', 'Only letters, numbers, spaces, dots, hyphens, and ampersands allowed.')])),
                ('cruise_no', models.CharField(help_text='Unique cruise number/identifier', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'Only letters, numbers, and hyphens allowed.')])),
                ('cruise_name', models.CharField(blank=True, help_text='Official name of the cruise', max_length=255, null=True)),
                ('period_from', models.DateField(blank=True, help_text='Cruise start date', null=True)),
                ('period_to', models.DateField(blank=True, help_text='Cruise end date', null=True)),
                ('chief_scientist_name', models.CharField(help_text='Name of the chief scientist', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s\\.\\-]+$', 'Only letters, spaces, dots, and hyphens allowed.')])),
                ('area', models.CharField(help_text='Geographic area/region of the cruise', max_length=255)),
                ('objective', models.TextField(help_text='Scientific objectives of the cruise')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('archived', 'Archived')], default='completed', help_text='Current status of the cruise', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the cruise', null=True)),
                ('files_link', models.CharField(blank=True, help_text='Path or link to associated cruise files', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cruise',
                'verbose_name_plural': 'Cruises',
                'ordering': ['-period_from'],
                'indexes': [models.Index(fields=['ship_name'], name='cruise_crui_ship_na_2a02ad_idx'), models.Index(fields=['cruise_no'], name='cruise_crui_cruise__2cde11_idx'), models.Index(fields=['chief_scientist_name'], name='cruise_crui_chief_s_8d54ab_idx'), models.Index(fields=['area'], name='cruise_crui_area_833886_idx'), models.Index(fields=['-period_from'], name='cruise_crui_period__6d8133_idx')],
            },
        ),
        migrations.CreateModel(
            name='CruiseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('report', 'Report'), ('data', 'Data'), ('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=20)),
                ('file_path', models.CharField(help_text='Relative path to the file in downloads folder', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cruise.cruise')),
            ],
            options={
                'verbose_name': 'Cruise File',
                'verbose_name_plural': 'Cruise Files',
                'ordering': ['file_name'],
                'indexes': [models.Index(fields=['cruise'], name='cruise_crui_cruise__9ebeb2_idx'), models.Index(fields=['file_type'], name='cruise_crui_file_ty_4b679e_idx')],
            },
        ),
    ]
